### ISSUE TITLE
Cannot disable looping with loop-p

### ISSUE THREAD

**Issue by TatriX** [defaultxr/cl-patterns#13]
Hi!
```lisp
(pb :foo
  :type :midi
  :channel 8
  :quant 1
  :dur 1
  :pfin 2
  :midinote 60)

(play :foo)
```
I assume this code should play 2 notes, but it loops forever. Am I missing something?

**Comment by defaultxr** [comment]
`pdef`s (which is what `pb` creates "under the hood") will loop by default. Normally it'd be possible to change that behavior by setting the `loop-p` slot to `nil`, however it looks like this is currently broken :) I'll have to fix this when I'm able to.

But yes, it is normal and expected that `pdef`s and thus `pb` will loop. Bare patterns will not, though. i.e. this will not loop:

```lisp
(play (pbind
       :type :midi
       :channel 8
       :quant 1
       :dur 1
       :pfin 2
       :midinote 60))
```

The reason pdefs loop by default is mostly because I almost always find myself wanting them to loop. In fact, that turning off their looping is broken right now goes to show how little I actually turn off the looping :)

I'll leave this issue open until I've fixed `loop-p`. Thanks for reporting!

**Comment by defaultxr** [comment]
True, that is one case where I specifically changed behavior from SC; in SC I would often find myself doing things like:

```
Pdef(\i, Pbind(\instrument, \default,
	\midinote, Pseq([50, 51, 52, 53], 1),
)).condition_(_.isNil);

Pdef(\j, Psym([\i]));

Pdef(\j).play;
```

The above makes it so that `\i` can be redefined and the new pattern will start playing at the end of its loop (`.condition_(_.isNil)`) rather than immediately starting over as soon as you redefine it (the default behavior; not very "musically useful" IMO) or at a specifically-set `quant` value.

Instead, switching to the new definition of the `i` pattern at the end of its loop is just the default behavior in cl-patterns.

And yes, this behavior is mentioned in the supercollider-example.lisp file. It's also mentioned in [sc-differences.org](https://github.com/defaultxr/cl-patterns/blob/master/doc/sc-differences.org) and [pdef's docstring](https://github.com/defaultxr/cl-patterns/blob/master/src/patterns/patterns.lisp#L1120). But you're right that it is a bit surprising especially since bare patterns still don't loop in cl-patterns.
