### ISSUE TITLE
None of the examples in the supercollider example work for me

### ISSUE THREAD

**Issue by cianoc** [defaultxr/cl-patterns#39]
I can load the library fine, and compile the synths. However when I tried to run a pattern from the version in quicklisp, it would complain that 
`There is no applicable method for the generic function`

So I tried the latest version in github instead, and I no longer get an error. However when I run the clock nothing happens. And if I try to call a synth directly as follows:
`(synth 'default)`

I get the error:
```
There is no applicable method for the generic function
  #<STANDARD-GENERIC-FUNCTION CL-COLLIDER::ID (2)>
when called with arguments
  (NIL).
   [Condition of type SB-PCL::NO-APPLICABLE-METHOD-ERROR]
```

This is on SBCL on the Mac (M1).

**Comment by defaultxr** [comment]
Hmm... I think I see the issue. After you run `(cl-patterns:backend-start 'supercollider)`, if you enter `cl-collider:*s*` into the REPL, does it show `NIL`?

I'm guessing that is the problem, and it seems to be because the `unless` on [this line](https://github.com/defaultxr/cl-patterns/blob/01b8d2952ff3e6c708c7a19cd776fc5ee304ff8c/src/backends/supercollider.lisp#L33) should be a `when` instead. You can edit it yourself but I'll also push a fix for that once I have a moment to double check.

**Comment by defaultxr** [comment]
I think that was probably the issue. Let me know if you're still having any problems after updating to the latest git master.

**Comment by cianoc** [comment]
Yes that fixed it for me. Sorry for not getting back sooner.

Thanks for fixing it!

**Comment by defaultxr** [comment]
No problem, and glad to hear it! And thanks for reporting :)
