### ISSUE TITLE
pdef and pb doesn't restart when re-evaluated

### ISSUE THREAD

**Issue by kflak** [defaultxr/cl-patterns#52]
I seem to remember reading somewhere that re-evaluating a pdef or a pb causes the new version to be picked up and played, but in my experience I need to stop the pattern first before I can play the new version of it. Is this possible or is my memory just faulty?

**Comment by defaultxr** [comment]
Patterns have infinite length by default, and changes to patterns are only picked up when the pattern ends. So if you write a pattern like this:

```lisp
(pb :foo
  :midinote (pseq '(60 62 64 65)))
```

The `pseq` has `:inf` as its default length, so any changes to `:foo` will not be heard until you stop and restart the pattern.

Instead, you could do something like:

```lisp
(pb :foo
  :midinote (pseq '(60 62 64 65) 1))
```

This will sound the same since the pattern will restart after the `pseq` ends. But since it ends, the pattern will play any changes at the end of each loop.

You can also use the special keys like `:pfin`, `:pfindur` , `:psync`, etc, to limit the duration, i.e.:

```lisp
(pb :foo
  :midinote (pseq '(60 62 64 70))
  :pfindur 4)
```

This is effectively equivalent to:

```lisp
(pdef :foo
      (pfindur (pbind :midinote (pseq '(60 62 64 70)))
               4))
```

You can also adjust the `*default-pattern-length*` and `*default-pattern-repeats*` variables if you don't want patterns to be `:inf` length by default.

**Comment by defaultxr** [comment]
Thinking about it now, maybe `:inf` should not be the default length for patterns. Does that seem like something that should be changed? Only issue is, I'm worried about breaking any patterns people have written in the past if that change is made.

**Comment by kflak** [comment]
Ah yes, that makes perfect sense! Actually I think the default behavior of :inf is a significant improvement over the inconsistency of the sclang patterns. Always bugged me that I have to memorize which patterns are infinite by default and which ones aren't....

**Comment by kflak** [comment]
Overall I'm very impressed by the implementation of this library :-) I really like the addition of the :pfindur and :quant keys in the patterns themselves. Just makes sense...

**Comment by defaultxr** [comment]
> Ah yes, that makes perfect sense! Actually I think the default behavior of :inf is a significant improvement over the inconsistency of the sclang patterns. Always bugged me that I have to memorize which patterns are infinite by default and which ones aren't....

Definitely, that was always something that tripped me up in SC as well. And also the inconsistent arguments order in patterns. Like `Pfindur` in SC is `Pfindur(dur, pattern, tolerance)`, but then `Psync` is `Psync(pattern, quant, maxdur, tolerance)`. Little things like that add up, especially for new users. And it probably doesn't help people who are live-coding to have to remember which pattern has the pattern first and then the params or vice-versa.

> Overall I'm very impressed by the implementation of this library :-) I really like the addition of the :pfindur and :quant keys in the patterns themselves. Just makes sense...

Thank you very much :) I always thought it would make it a lot easier to be able to affect patterns this way. In fact, back when I was using vanilla SC I wrote a few custom pattern classes to try to implement similar functionality. It's definitely much nicer to implement things in Lisp though. Having to rebuild the class library after every change was such a pace-breaker. But yeah, thanks again, and glad you're enjoying the library :)

**Comment by kflak** [comment]
Yes, the coding experience in common lisp is (potentially) a few orders of magnitude above the sclang experience, especially when using emacs... Still struggling with the basics, though, but I'm starting to get the hang of enough to become productive. It's very addictive.

Closing the issue now, unless you feel like keeping it open for further discussion about the pattern default length? Or maybe better to move that to a separate discussion topic?

**Comment by defaultxr** [comment]
> Yes, the coding experience in common lisp is (potentially) a few orders of magnitude above the sclang experience, especially when using emacs... Still struggling with the basics, though, but I'm starting to get the hang of enough to become productive. It's very addictive.

Addictive indeed :) It does take a bit of getting used to when you're starting out, but once you get past the initial challenges then I think you can get a lot more done in Lisp a lot faster than in many other languages.

> Closing the issue now, unless you feel like keeping it open for further discussion about the pattern default length? Or maybe better to move that to a separate discussion topic?

Nah, should be good to close it now. I'll go ahead and do that. Thanks!

**Comment by defaultxr** [comment]
Oh, one more thing - it's also possible (for some patterns at least - I haven't verified it with all of them yet) to provide a function of zero arguments as the value for a parameter. The function will then be evaluated for each output of the pattern, such that changes affecting the result of that function are heard immediately.

For example, if you evaluate the following:

```lisp
(defparameter *foo* (list 60 62 64 65))

(pb :main
  :instrument :default
  :midinote (pseq (lambda () *foo*) :inf)
  :dur 1)

(play (pdef :main))
```

This starts an infinite-length pattern which never ends. Normally you'd need to stop and re-start the pattern to hear any changes, but since the `pseq`'s LIST is a function that returns the value of `*foo*`, you can instead just change the value of `*foo*`:

```lisp
(setf *foo* (list 50 52 54 55))
```

And the change will be heard immediately, regardless of where in the list the `pseq` was at.

This works at least for `pseq`, and probably other patterns as well, but I don't think I've set up a test to ensure it works for all pattern types yet, so there are probably some it doesn't work for.

**Comment by kflak** [comment]
Wow, that is pure awesomeness! Thanks for the tip, I'm pretty sure I will use this a lot.
