### ISSUE TITLE
Shouldn't pk have a repeats argument?

### ISSUE THREAD

**Issue by ntrocado** [defaultxr/cl-patterns#53]
This just tripped me up:

``` lisp
CL-PATTERNS> (next-upto-n (pbind :a 1 :b 2 :c (pseq (list (pk :a) (pk :b)))) 4)
((EVENT :A 1 :B 2 :C 1) (EVENT :A 1 :B 2 :C 1) (EVENT :A 1 :B 2 :C 1)
 (EVENT :A 1 :B 2 :C 1))
```

I was expecting `:C` to alternate between 1 and 2.

This works:
``` lisp
CL-PATTERNS> (next-upto-n (pbind :a 1 :b 2 :c (pseq (list (pfin (pk :a) 1) (pfin (pk :b) 1)))) 4)
((EVENT :A 1 :B 2 :C 1) (EVENT :A 1 :B 2 :C 2) (EVENT :A 1 :B 2 :C 1)
 (EVENT :A 1 :B 2 :C 2))
```

Maybe we need a `repeats` argument [as in SuperCollider](https://doc.sccode.org/Classes/Pkey.html)?

**Comment by defaultxr** [comment]
Good call, yes, a `repeats`/`length` would be much more useful than `default` as the second argument of `pk`. Especially since I don't think I've ever even used `default` other than in the tests for `pk`.

Since `length` is probably common enough, but `repeats` and `length` are the last argument of a pattern (for consistency), I've replaced the `default` argument of `pk` with `length`, but also added a `pk*` pattern which has `key`, `default`, and `length` as its arguments, in case `default` is still needed.
