### ISSUE TITLE
How to perform operations on `event-values` that return lists?

### ISSUE THREAD

**Issue by kflak** [defaultxr/cl-patterns#54]
In sclang I'm used to being able to do something like this:
```sclang
p = Pbind(
    \instrument, \pmFB,
    \freq, [220, 440],
    \modfreq, Pfunc{|ev| ev.use{~freq.() * rrand(0.99, 1.01)}},
...etc
```
In cl-patterns I was hoping to translate this into

```common-lisp
    :freq (list 220 440)
    :mod-freq (pf (event-value *event* :freq))
``` 
but this causes cl to blow up, as it expects a number, and not a list... Instead I'm reduced to calculating the relevant frequencies in advance, stuffing them in an external variable, and grabbing it from there: 

```common-lisp
(defparameter *dorian-chords* (list (list -7 0 4 7 9)    ; Am
                                    (list -7 0 5 7 9)    ; F3o/A
                                    (list -7 0 4 7 9)    ; Am
                                    (list -7 0 5 7 9)    ; F3o/A
                                    (list -7 0 5 7 10))) ; D
(defparameter *dorian-octave* 3)
(defparameter *dorian-root* -3)
(defparameter *dorian-chord-freqs*
  (loop
    for chord in *dorian-chords*
    collect (loop
              for degree in chord
              collect (* (random-range 1.99 2.01)
                         (degree-freq degree
                                      :root *dorian-root*
                                      :octave *dorian-octave*
                                      :scale :dorian)))))
```
which I guess is kind of ok-ish, but not very succinct. Is there a better and more concise way of accomplishing this within a pattern?

**Comment by defaultxr** [comment]
Hmm... Sorry if I'm misunderstanding, but I think your sclang code could be translated to something like this:

```lisp
(pb :test
  :instrument :pmFB
  :freq (list 220 440)
  :modfreq (p* (pk :freq)
               (pclump (pwhite 0.99 1.01) 2)))
```

The `pclump` will to grab 2 outputs from the `pwhite` and yield them together as a 2-element list, which can then be multiplied with the `:freq` by way of `pk` and `p*`. So `pf` is not necessary and thus you don't have to manually multiply lists together... Though you could also do something like this:

```lisp
(pb :test
  :instrument :pmFB
  :freq (list 220 440)
  :freq (pf (mutility:mapshort '*
                            (event-value *event* :freq)
                            (mutility:a (random-range 0.99 1.01)!2))))
```

But basically, the pattern system should handle "multi-channel expansion" properly (in theory anyway, let me know if you hit any bugs with that, but I think most of them are ironed out at this point). So if you are able to stick with patterns rather than dropping back to standard CL functions, you shouldn't have to manually handle lists; it should handle them for you.

Let me know if I'm misunderstanding anything though. I didn't have a chance to look too deeply into your third snippet at the moment but I wanted to at least answer the first part. I should be able to dedicate more time to it tomorrow I think if what I wrote above doesn't answer your full question.

(Also, cl-patterns has functions `chord`, `scale`, and `tuning` built in (which have a library of most common scales/etc). Ideally those would be enough so that you don't have to write out chords/scales manually, but if not, or if you find any issues with that functionality, please let me know - I want to make sure they're good enough for musical use, but I don't actually use a lot of chords/scales in my own music so I'm not sure they've really been tested out as thoroughly as they should have been. :)

**Comment by kflak** [comment]
Very elegant solution :-) It works when I specify the pitches as `:freq`, but I haven't found a way to specify them as `:degree`, though, which means I still have to calculate the frequencies manually. The chord keys are very cool, but as far as I can see they are only giving the main notes and don't really provide a way of extending them with doublings and inversions etc. , so I still prefer to provide them as lists.

```common-lisp
   (defparameter *dorian-chords* (list (list -7 0 4 7 9)    ; Am
                                    (list -7 0 5 7 9)    ; F#o/A
                                    (list -7 0 4 7 9)    ; Am
                                    (list -7 0 5 7 9)    ; F#o/A
                                    (list -7 0 5 7 10))) ; D
(defparameter *dorian-octave* 3)
(defparameter *dorian-root* -3)
(defparameter *dorian-chord-freqs*
  (loop
    for chord in *dorian-chords*
    collect (loop
              for degree in chord
              collect (degree-freq degree
                                   :root *dorian-root*
                                   :octave *dorian-octave*
                                   :scale :dorian))))

;; In the pdef:
       ;; :degree (pseq *dorian-chords*) ;; doesn't work
       :freq (pseq *dorian-chord-freqs*) ;; works
       :mod-freq (p* (pk :freq)
                        (pclump (pwhite 0.99 1.01) 5))
```

Using the :freq key on the :degree gives me this error:

```common-lisp
The value
  (-7 0 4 7 9)
is not of type
  NUMBER
```
... which obviously is true. I'm just curious about where in the chain the conversion of degree to freq happens, so that it would be possible to treat a degree as a freq with pk?

Another question, while I'm at it: is there a way to specify programmatically the clump length? I could, of course, just use a pseq for this, but it would be more elegant to be able to retrieve the length of the incoming list directly.

**Comment by defaultxr** [comment]
> The chord keys are very cool, but as far as I can see they are only giving the main notes and don't really provide a way of extending them with doublings and inversions etc. , so I still prefer to provide them as lists.

Doublings and inversions... That is not something I'm familiar with to be honest (it's embarrassing how little I know about theory). If you implement that functionality I think it would be good to have in the library, if you want to submit a PR--especially if it works with the existing `chord`/`scale`/`tuning` functionality. Otherwise I'll probably do some research on those at some point and see if I can write them and any related functionality I can find.

> ```commonlisp
>    (defparameter *dorian-chords* (list (list -7 0 4 7 9)    ; Am
>                                     (list -7 0 5 7 9)    ; F#o/A
>                                     (list -7 0 4 7 9)    ; Am
>                                     (list -7 0 5 7 9)    ; F#o/A
>                                     (list -7 0 5 7 10))) ; D
> (defparameter *dorian-octave* 3)
> (defparameter *dorian-root* -3)
> (defparameter *dorian-chord-freqs*
>   (loop
>     for chord in *dorian-chords*
>     collect (loop
>               for degree in chord
>               collect (degree-freq degree
>                                    :root *dorian-root*
>                                    :octave *dorian-octave*
>                                    :scale :dorian))))
> 
> ;; In the pdef:
>        ;; :degree (pseq *dorian-chords*) ;; doesn't work
>        :freq (pseq *dorian-chord-freqs*) ;; works
>        :mod-freq (p* (pk :freq)
>                         (pclump (pwhite 0.99 1.01) 5))
> ```
> 
> Using the :freq key on the :degree gives me this error:
> 
> ```commonlisp
> The value
>   (-7 0 4 7 9)
> is not of type
>   NUMBER
> ```

Should be fixed in 9403bd0dc3a78eeffa34d011f2a29dd4c626c140 - thanks!

> ... which obviously is true. I'm just curious about where in the chain the conversion of degree to freq happens, so that it would be possible to treat a degree as a freq with pk?

Conversions like that are handled in `event`-related functions, since they are `*event-special-keys*`. So it doesn't even have to be in a pattern. i.e. This works (now, after I fixed the bug you pointed out):

```lisp
> (event-value (event :degree (list 0 1 2 3)) :freq)
(523.2511306011972d0 587.3295358348151d0 659.2551138257398d0
 698.4564628660078d0)
:DEGREE
```

> Another question, while I'm at it: is there a way to specify programmatically the clump length? I could, of course, just use a pseq for this, but it would be more elegant to be able to retrieve the length of the incoming list directly.

There's `paclump` which automatically clumps outputs into lists based on the length of the longest list in `*event*` (i.e. the longest list that has been defined in the pattern). So you don't have to manually specify the clump size, it will grab as many as it needs to match what it thinks is the current list length.

i.e.

```lisp
(pb :test
  :degree (pseq *dorian-chords* 1)
  :mod-freq (p* (pk :freq)
                (paclump (pwhite 0.99 1.01))))
```

Will now work, and with `paclump` you can make each list in `*dorian-chords*` any size you want and `paclump` will grab the correct number of outputs from the `pwhite` automatically.

**Comment by kflak** [comment]
Awesome, great, fantastic (starting to run out of superlatives here...) !

I feel your pain re. music theory. I was plunged into it a couple of years ago when I started studying audiovisual composition after decades of winging it on my own and I had to take harmony and solfego courses. It was terrifying.

I think the inversions are probably the easiest to program, they could simply be specified with an additional bass note, like so: C/E, which means a C major with an E in the bass, which give the degrees 2 4 7 instead of 0 2 4. Doubling of notes in a chord is simply the doubling of one or more of its members in a different octave. Don't know of any ways to notate that in  an easy way, as there are simply so many options. I'll quietly start adding in inversions to the library when I have a bit of time.

**Comment by kflak** [comment]
Ah, looking at the actual code now... As the names aren't hardcoded for each chord, then it would probably make more sense to add a parameter called something like :inversion n, which would cause the degrees to rotate and shift up the relevant notes by an octave. So fx. for the 1st inversion you would shift up the 0th element, for the 2d the 0th and 1st, etc.

**Comment by defaultxr** [comment]
> I feel your pain re. music theory. I was plunged into it a couple of years ago when I started studying audiovisual composition after decades of winging it on my own and I had to take harmony and solfego courses. It was terrifying.

I would imagine so! I've only been in one class relating to music back when I was in college but we never got too deep into actual theory, unfortunately. For me, the problem is that I have a patchy understanding of theory, and when I try to look up information on it, I often end up finding resources that start by explaining things I already know. It seems difficult to find a good resource with information on the "intermediate" levels of it that I'm not as familiar with.

Plus, since I'm coding software relating to theory, I'm more interested in the actual mathematical relationships/algorithms that would be used to implement theory-related functionality. And most resources don't really approach it from that angle. I've found a few "music theory for programmers" type resources though, which I'll hopefully have some time to go through in the future.

> I think the inversions are probably the easiest to program, they could simply be specified with an additional bass note, like so: C/E, which means a C major with an E in the bass, which give the degrees 2 4 7 instead of 0 2 4. Doubling of notes in a chord is simply the doubling of one or more of its members in a different octave. Don't know of any ways to notate that in an easy way, as there are simply so many options. I'll quietly start adding in inversions to the library when I have a bit of time.

Oh, I think that makes sense regarding the inversions. I may have to study it a bit more, especially if you contribute it as code to the library :) I'm not sure about the doubling notation, but maybe the basic doubling could first be done as a function with each parameter as a separate argument, and then a function could be written that takes a shorter/"sweeter" notation and translates it to the longer more precise notation of the main doubling functionality, effectively "wrapping" it.

> Ah, looking at the actual code now... As the names aren't hardcoded for each chord, then it would probably make more sense to add a parameter called something like :inversion n, which would cause the degrees to rotate and shift up the relevant notes by an octave. So fx. for the 1st inversion you would shift up the 0th element, for the 2d the 0th and 1st, etc.

Ah, I think I see what you mean; adding another parameter to the `scale` function in other words? I wouldn't be opposed to that. It should probably be a keyword argument though since there are probably other transformations that could be implemented in the future (at least, I assume). The only problem is that since scales are actual objects defined by classes, and the objects contain the name of the scale, the altered scale would probably have to be cloned from the existing one, and then the clone's `name` and `notes` changed appropriately. So maybe something like:

```lisp
(defun scale-inversion (scale n)
  "Get SCALE's Nth inversion."
  (let* ((scale-notes (copy-list (scale-notes old-scale)))
         (inverted-scale-notes (blah-blah scale-notes)))
    (make-instance 'scale :name (format nil "~A: ~:R inversion" (scale-name old-scale) n)
                          :notes inverted-scale-notes
                          :tuning (scale-tuning))))
```

And then this function could be called from the `scale` function somehow.

Usually `define-scale` is used, but that macro also adds the scale to the `*scales*` hash, which I don't think we want to do for "temporary" scales like this which are just altered versions of existing ones. So in this case just `make-instance` is probably fine (at least, that is how I would do it).

**Comment by kflak** [comment]
No worries about late responses, I'm also in the middle of preparing for performance as well as various life obligations, so I understand *completely* :-) (which is why I also have limited time to contribute directly to the library. I'm not a programmer by trade, so it takes me a while to understand a code base, and right now I'm trying to work as much as possible with creating sound with cl-{collider,patterns} rather than heavy programming to get a more intuitive feel for how it works, while reading up as much as I can about common lisp... But as soon as I have a bit more of a breather from all of that I will certainly start contributing! I really love the workflow that is emerging from all of this... and the language is fantastic.)

So, to understand a  bit better: the chords depend on the (temporary) scale, so the best way to go about inverting the chords is to tackle if from the scale end? The interesting bit is that by doing this you could also get all the various modes of the major scale for free: Ionian at index 0, dorian at index 1, phrygian at 2, lydian at 3, mixolydian at 4, aeolian at 5, and locrian at 6. Check [this resource](https://theoryandsound.com/modes-of-the-major-scale/) for more...
