### ISSUE TITLE
Compiling with swank and later loading without fails

### ISSUE THREAD

**Issue by Yehouda** [defaultxr/cl-patterns#7]
If you compile **cl-patterns** with **swank** loaded (i.e. **ql:quickload** it the first time), then later loading it without **swank** errors, because it looks for symbols in the "SWANK" package. That is because of the conditionalization of **swank::compute-enriched-decoded-arglis**  in src/patterns/patterns.lisp.

Probably the best approach is to have a "swank-support.lisp" file, and use it only when swank is loaded.

**Comment by defaultxr** [comment]
Thanks for figuring this out, similar errors have occurred for me before occasionally but I wasn't fully sure of the cause since I figured using `#+swank` to conditionalize should work. It makes sense now since compilation and loading aren't the same thing.

I've separated out the swank functionality to a separate file as per your suggestion and loaded it with an `eval-when`. This seems to fix the issue. Let me know if you see any other problems.
