### ISSUE TITLE
Can't build supercollider system

### ISSUE THREAD

**Issue by quicklisp** [defaultxr/cl-patterns#9]
Log here: http://report.quicklisp.org/2020-09-21/failure-report/cl-patterns.html#cl-patterns_supercollider

I get this: `The function CL-PATTERNS::AFFIXNEW is undefined.`

**Comment by defaultxr** [comment]
That's embarrassing. I went ahead and reverted the use of `affixnew` and pushed the change which I believe should allow this to build properly again.

`affixnew` should be exported by the `mutility` system which is `:use`ed by `cl-patterns`, however it was added since the last quicklisp dist update, so I guess you're building cl-patterns based on the old `mutility`?

(I also didn't realize you were building the `cl-patterns` sub-systems as well; thought you only built the main `cl-patterns` system for quicklisp...)

In any case, I'm noting those things for the future, and apologies for wasting your time. Hopefully you won't get any more errors but let me know if you do.

**Comment by quicklisp** [comment]
I always try to build every system in a project, and always try to use the latest commits or releases (which can vary depending on the preferences of the author). So I've been building with the latest mutility as far as I know.

**Comment by defaultxr** [comment]
Oh okay, you must just skip the systems that don't build due to missing dependencies, then? Since I'm seeing the `cl-patterns/incudine` and `cl-patterns/alsa-midi` systems are failing due to missing dependencies which afaik have never been in Quicklisp.

In the future I'll add the sub-systems to my CI tests, and will see about monitoring the quicklisp RSS feeds. Thanks for informing me of the failure.

**Comment by quicklisp** [comment]
Right - if they don't build, they don't end up in Quicklisp.

Thanks for fixing things!
